name = "kpi-duo"
compatibility_date = "2024-11-21"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "kpi-duo-db"
database_id = "" # wrangler d1 create kpi-duo-db で取得

# KVストレージ設定（キャッシュ用）
[[kv_namespaces]]
binding = "CACHE"
id = "" # wrangler kv:namespace create CACHE で取得

# Cronトリガー（毎朝9時JST = 0時UTC）
[triggers]
crons = ["0 0 * * *"]

