name = "kpi-duo"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "kpi-duo-db"
database_id = "68dc396c-4fbf-41f8-b4ce-a46db08d5d26"

